interface TechnicianInterface {
  AADHAR_NUMBER: number; // Numeric Aadhar number
  ADDRESS_LINE1: string;
  ADDRESS_LINE2: string | null;
  ARCHIVE_FLAG: string;
  ASSIGNED_DATE: string | null;
  AVG_RATINGS: number;
  CAN_ACCEPT_JOB: number;
  CAN_ASSIGN_EXPRESS_ORDER: number;
  CAN_ASSIGN_ORDERS_FORCEFULLY: number;
  CAN_EDIT_PINCODE: number;
  CAN_EDIT_SKILL: any;
  CAN_VIEW_JOB_POOL: number;
  CAN_VIEW_SERVICE_PRICES_SUMMARY: number;
  CITY_ID: number | null;
  CITY_NAME: string | null;
  CLIENT_ID: number;
  CLOUD_ID: string;
  CONTRACT_END_DATE: string | null;
  CONTRACT_START_DATE: string | null;
  COUNTRY_CODE: string;
  COUNTRY_ID: number;
  COUNTRY_NAME: string;
  CREATED_DATE: string;
  CREATED_MODIFIED_DATE: string;
  CURRENT_STATUS: string | null;
  DEVICE_ID: string;
  DISTRICT_ID: number;
  DISTRICT_NAME: string;
  DOB: string;
  EMAIL_ID: string;
  EXPERIENCE_LEVEL: string;
  FIREBASE_REG_TOKEN: string | null;
  GENDER: string;
  HOME_LATTITUDE: string; // Could also be number if preferred
  HOME_LONGITUDE: string; // Could also be number if preferred
  ID: number;
  IS_ACTIVE: number;
  IS_OWN_VEHICLE: number;
  IS_TOOLKIT_ASSIGNED: number | null;
  IS_UNIFORM_ASSIGNED: number | null;
  LETEST_REVIEW: number;
  MOBILE_NUMBER: string;
  NAME: string;
  PASSWORD: string | null;
  PHOTO: string;
  PINCODE: string;
  PINCODE_ID: string;
  PREFERRED_LANGUAGE_ID: number | null;
  PROFILE_PHOTO: string | null;
  READ_ONLY: string;
  REPORTING_PERSON_ID: number | null;
  REPORTING_PERSON_NAME: string | null;
  SESSION_KEY: string;
  STATE_ID: number;
  STATE_NAME: string;
  TECHNICIAN_STATUS: number;
  TYPE: string;
  VEHICLE_DETAILS: string;
  VEHICLE_NO: string;
  VEHICLE_TYPE: string;
  VENDOR_ID: number | null;
  VENDOR_NAME: string | null;
  W_CLOUD_ID: string | null;
}

interface PartSubCategorirs {
  ARCHIVE_FLAG: string;
  CATEGORY_NAME: string;
  CLIENT_ID: number;
  CREATED_MODIFIED_DATE: string;
  DESCRIPTION: string;
  ICON: string;
  ID: number;
  INVENTRY_CATEGORY_ID: number;
  IS_ACTIVE: number;
  NAME: string;
  READ_ONLY: string;
  SEQ_NO: number;
}

interface InventoryItemOld {
  ADDRESS_LINE1: string;
  ADDRESS_LINE2: string | null;
  ALERT_STOCK_LEVEL: number;
  ARCHIVE_FLAG: string;
  AVG_LEVEL: number;
  BASE_QUANTITY: number;
  BASE_UNIT_ID: number;
  BASE_UNIT_NAME: string;
  CLIENT_ID: number;
  CREATED_MODIFIED_DATE: string;
  DATE_OF_ENTRY: string;
  DESCRIPTION: string;
  EXPIRY_DATE_ALLOWED: number;
  GUARANTEE_ALLOWED: number;
  HSN_ID: number;
  HSN_NAME: string;
  ID: number;
  IMAGE_URL: string | null;
  IMAGE_URL_2: string | null;
  IMAGE_URL_3: string | null;
  IMAGE_URL_4: string | null;
  INVENTORY_CATEGORY_ID: number;
  INVENTORY_CATEGORY_NAME: string;
  INVENTORY_TRACKING_TYPE: string;
  INVENTRY_SUB_CATEGORY_ID: number;
  INVENTRY_SUB_CATEGORY_NAME: string;
  IS_HAVE_VARIANTS: number;
  IS_NEW: number;
  IS_SET: number;
  ITEM_NAME: string;
  LOCATION_ID: number | null;
  LOCATION_NAME: string | null;
  MOBILE_NO: string;
  NAME: string;
  PARENT_ID: number;
  PURCHASE_PRICE: number | null;
  QUANTITY: number | null;
  READ_ONLY: string;
  REMARKS: string | null;
  REORDER_STOCK_LEVEL: number;
  SELLING_PRICE: string;
  SHORT_CODE: string;
  SKU_CODE: string;
  STATUS: number;
  TAX_ID: number;
  TAX_NAME: string;
  TAX_PREFERENCE: string;
  UNIT_ID: number;
  UNIT_NAME: string;
  VARIANT_COMBINATION: string | null;
  WAREHOUSE_ID: string;
  WAREHOUSE_MANAGER_ID: number;
  WAREHOUSE_MANAGER_NAME: string;
  WAREHOUSE_NAME: string;
  WARRANTY_ALLOWED: number;
}
interface InventoryItem {
  ARCHIVE_FLAG: any;
  BATCH_NO: string | null;
  CLIENT_ID: number;
  CREATED_MODIFIED_DATE: string;
  DATE: string;
  ID: number;
  INVENTORY_CAT_ID: number;
  INVENTORY_CAT_NAME: string;
  INVENTORY_ID: number;
  INVENTORY_NAME: string;
  INVENTORY_TRACKING_TYPE: string | null;
  INVENTORY_TYPE: string;
  INVENTROY_SUB_CAT_ID: number;
  INVENTROY_SUB_CAT_NAME: string;
  IS_VARIENT: number;
  MOVEMENT_ID: number;
  MOVEMENT_NUMBER: string;
  MOVEMENT_TYPE: string;
  PARENT_ID: number;
  QUANTITY: number;
  QUANTITY_PER_UNIT: number;
  READ_ONLY: string;
  REASON: string | null;
  SELLING_PRICE: number;
  SERIAL_NO: string;
  STATUS: number;
  TECHNICIAN_ID: number;
  TECHNICIAN_NAME: string;
  TRANSFER_MODE: string;
  UNIT_ID: number;
  UNIT_NAME: string;
  USER_ID: number;
  USER_NAME: string;
  VARIANT_NAME: string;
  WAREHOUSE_ID: number;
  WAREHOUSE_NAME: string;
  IS_MANUAL: boolean;
}

interface Job {
  id: string;
  title: string;
  scheduledTime: string;
  estimatedTime: string;
  status: string;
  usedTime: string;
  paymentMode: string;
  details: {
    serviceType: string;
    description: string;
    priority: string;
  };
  customer: {
    name: string;
    phone: string;
    address: string;
    latitude: 18.5634;
    longitude: 73.8123;
  };
  payment: {
    baseAmount: number;
    tax: number;
    total: number;
  };
  photos: {
    uri: string;
  }[];
}

interface JobData {
  IS_PARENT: number;
  FINAL_ITEM_AMOUNT: string | null;
  SPECIAL_INSTRUCTIONS: string | null;
  ARCHIVE_FLAG: string;
  ASSIGNED_DATE: string | null;
  CLIENT_ID: number;
  CREATED_MODIFIED_DATE: string | null;
  CUSTOMER_COUNTRY_CODE: string;
  CUSTOMER_ID: number;
  CUSTOMER_MOBILE_NUMBER: string;
  CUSTOMER_NAME: string;
  CUSTOMER_RATING: string;
  CUSTOMER_EMAIL: string;
  CUSTOMER_STATUS: string;
  CUSTOMER_TYPE: string;
  END_TIME: string | null;
  ESTIMATED_TIME_IN_MIN: number;
  EXECUTION_DATE_TIME: string | null;
  EXPECTED_DATE_TIME: string;
  HAPPY_CODE: string | null;
  ID: number;
  JOB_CARD_ID: number;
  IS_JOB_COMPLETE: number;
  INVENTORY_REQUESTED: any; // Adjust type as needed
  JOB_CARD_NO: string;
  JOB_CARD_NUMBER: string;
  JOB_CARD_STATUS: string;
  JOB_COMPLETED_DATETIME: string | null;
  JOB_CREATED_DATE: string;
  JOB_STATUS_ID: number;
  LATTITUTE: number;
  LOCATION_LATITUDE: number;
  LOCATION_LONG: number;
  LONGITUDE: number;
  ORDER_DATE_TIME: string;
  ORDER_DETAILS_ID: number;
  ORDER_ID: number;
  ORDER_NO: string;
  ORDER_NUMBER: string;
  ORDER_STATUS: string;
  ORDER_STATUS_NAME: string;
  ORGNISATION_ID: number | null;
  PINCODE: string;
  PAYMENT_MODE: string;
  PAYMENT_STATUS: string;
  PRIORITY: any; // Adjust type if needed
  READ_ONLY: string;
  EXPRESS_DELIVERY_CHARGES: string;
  COUPON_AMOUNT: string;
  SCHEDULED_DATE_TIME: string;
  SERVICE_ADDRESS: string;
  SERVICE_AMOUNT: string;
  SERVICE_FULL_NAME: string;
  SERVICE_ID: number;
  SERVICE_NAME: string;
  SERVICE_IMAGE: string;
  SERVICE_SKILLS: string;
  START_TIME: string | null | any;
  STATUS: string;
  TASK_DESCRIPTION: string;
  TECHNICIAN_COST: string;
  TECHNICIAN_ID: number;
  TECHNICIAN_NAME: string | null;
  TECHNICIAN_RATING: string;
  TECHNICIAN_STATUS: string;
  TERRITORY_ID: number;
  TERRITORY_NAME: string;
  TOTAL_AMOUNT: string;
  TAX_AMOUNT: string;
  SERVICE_BASE_PRICE: string;
  TAX_RATE: string;
  TRACK_STATUS: any; // Adjust type if needed
  USER_ID: number;
  USER_NAME: string;
  VENDOR_COST: string;
  VENDOR_ID: number | null;
  VENDOR_NAME: string | null;
  MODEL_NUMBER: string | null;
  DESCRIPTION: string | null;
  BRAND_NAME: string | null;
  PHOTO_FILE: string | null;
  USED_TIME: string;
  REMARK: string | null;
  IS_INVOICE_GENERATED: number;
}

interface JobPhotos {
  ARCHIVE_FLAG: string;
  CLIENT_ID: number;
  CREATED_MODIFIED_DATE: string;
  CUSTOMER_ID: number;
  ID: number;
  IS_IN_SEVICE?: boolean | null;
  JOB_CARD_ID: number;
  ORDER_ID: number;
  PHOTOS_URL: string;
  READ_ONLY: string;
  REMARK?: string | null;
  STATUS: string;
  TECHNICIAN_ID: number;
  UPLOADED_DATE_TIME: string;
}
interface RescheduleReasons {
  ARCHIVE_FLAG: string;
  CLIENT_ID: number;
  CREATED_MODIFIED_DATE: string;
  ID: number;
  IS_ACTIVE: number;
  READ_ONLY: string;
  REASON: string;
  TYPE: string;
}
type TechnicianEarnings = {
  JOB_WISE_EARNINGS: any[];
  TOTAL_EARNINGS: string | null;
  code: number;
  count: number;
  message: string;
};
interface JOB_WISE_EARNINGS {
  ASSIGNED_DATE: string;
  ID: number;
  JOB_CARD_NO: string;
  JOB_COMPLETED_DATETIME: string;
  TECHNICIAN_COST: string;
  TECHNICIAN_ID: number;
  TECHNICIAN_NAME: string;
}

interface JobList {
  ARCHIVE_FLAG: string;
  ASSIGNED_DATE: string;
  BRAND_NAME: string | null;
  CLIENT_ID: number;
  CREATED_MODIFIED_DATE: string | null;
  CUSTOMER_COUNTRY_CODE: string;
  CUSTOMER_ID: number;
  CUSTOMER_MOBILE_NUMBER: string;
  CUSTOMER_NAME: string;
  CUSTOMER_RATING: string;
  CUSTOMER_STATUS: string;
  CUSTOMER_TYPE: string;
  DESCRIPTION: string | null;
  END_TIME: string;
  ESTIMATED_TIME_IN_MIN: number;
  EXECUTION_DATE_TIME: string | null;
  EXPECTED_DATE_TIME: string;
  HAPPY_CODE: string | null;
  ID: number;
  INVENTORY_REQUESTED: string | null;
  IS_JOB_COMPLETE: string | null;
  JOB_CARD_NO: string;
  JOB_CARD_STATUS: string;
  JOB_COMPLETED_DATETIME: string | null;
  JOB_CREATED_DATE: string;
  JOB_PAUSED_DATETIME: string | null;
  JOB_RESUMED_DATETIME: string | null;
  JOB_STATUS_ID: number;
  LATTITUTE: string;
  LOCATION_LATITUDE: string;
  LOCATION_LONG: string;
  LONGITUDE: string;
  MODEL_NUMBER: string | null;
  ORDER_DATE_TIME: string;
  ORDER_DETAILS_ID: number;
  ORDER_ID: number;
  ORDER_NO: string;
  ORDER_STATUS: string;
  ORDER_STATUS_NAME: string;
  ORGNISATION_ID: number;
  PAYMENT_MODE: string;
  PAYMENT_STATUS: string;
  PHOTO_FILE: string | null;
  PINCODE: string;
  PRIORITY: string | null;
  READ_ONLY: string;
  REMARK: string | null;
  SCHEDULED_DATE_TIME: string;
  SERVICE_ADDRESS: string;
  SERVICE_AMOUNT: string;
  SERVICE_FULL_NAME: string;
  SERVICE_ID: number;
  SERVICE_NAME: string;
  SERVICE_SKILLS: string;
  START_TIME: string;
  STATUS: string;
  TASK_DESCRIPTION: string;
  TECHNICIAN_COST: string;
  TECHNICIAN_ID: number;
  TECHNICIAN_NAME: string;
  TECHNICIAN_RATING: string;
  TECHNICIAN_STATUS: string;
  TERRITORY_ID: number;
  TERRITORY_NAME: string;
  TOTAL_AMOUNT: string;
  TRACK_STATUS: string | null;
  USED_TIME: string | null;
  USER_ID: number;
  USER_NAME: string;
  VENDOR_COST: string;
  VENDOR_ID: number | null;
  VENDOR_NAME: string | null;
}
interface HELP_DOCUMENT {
  ARCHIVE_FLAG: string;
  CATEGORY_ID: number | null;
  CLIENT_ID: number;
  CREATED_MODIFIED_DATE: string;
  DOCUMENT: string;
  HELP_CATEGORY_NAME: string | null;
  HELP_DOCUMENT_SUB_CATEGORY_NAME: string | null;
  ID: number;
  LINK: string;
  MASTER_ID: number;
  MASTER_NAME: string;
  READ_ONLY: string;
  SERVICE_ID: number;
  STATUS: number;
  SUBCATEGORY_ID: number | null;
  TYPE: string;
}
interface partListDetail {
  ACTUAL_UNIT_ID: number | null;
  ACTUAL_UNIT_NAME: string | null;
  ARCHIVE_FLAG: string;
  BATCH_NO: string;
  CLIENT_ID: number;
  CREATED_MODIFIED_DATE: string;
  CUSTOMER_ID: number;
  ID: number;
  INVENTORY_CATEGORY_NAME: string | null;
  INVENTORY_ID: number;
  INVENTORY_NAME: string;
  INVENTRY_SUB_CATEGORY_NAME: string | null;
  ITEM_ID: number | null;
  JOB_CARD_ID: number;
  JOB_CARD_NO: string;
  ORDER_ID: number;
  ORDER_NO: string;
  PAYMENT_STATUS: string;
  QUANTITY: number;
  RATE: string;
  READ_ONLY: string;
  REMARK: string;
  REQUESTED_DATE_TIME: string;
  REQUEST_MASTER_ID: number;
  SERIAL_NO: string | null;
  STATUS: string;
  TAX_RATE: string;
  TECHNICIAN_ID: number;
  TECHNICIAN_NAME: string;
  TOTAL_AMOUNT: string;
  WAREHOUSE_ID: number;
}
interface JobRescheduleData {
  ARCHIVE_FLAG: string;
  ASSIGNED_DATE: string | null;
  CLIENT_ID: number;
  CREATED_MODIFIED_DATE: string;
  CUSTOMER_ID: number;
  CUSTOMER_NAME: string;
  END_TIME: string | null;
  ESTIMATED_TIME_IN_MIN: number;
  EXPECTED_DATE_TIME: string;
  ID: number;
  IS_RESCHEDULED: number;
  JOB_CARD_ID: number;
  JOB_CARD_NO: string;
  JOB_CARD_STATUS: string;
  JOB_CREATED_DATE: string;
  JOB_STATUS: string;
  MOBILE_NO: string;
  ORDER_ID: number;
  ORDER_NO: string;
  READ_ONLY: string;
  REASON: string;
  REMARK: string;
  REQUESTED_DATE: string;
  SCHEDULED_DATE_TIME: string | null;
  SERVICE_ADDRESS: string;
  SERVICE_AMOUNT: string;
  SERVICE_FULL_NAME: string;
  SERVICE_ID: number;
  SERVICE_NAME: string;
  START_TIME: string | null;
  STATUS: string;
  TECHNICIAN_ID: number;
  TECHNICIAN_NAME: string | null;
  TECHNICIAN_STATUS: string;
  TERRITORY_ID: number;
  TERRITORY_NAME: string;
}
